server:
  http2.enabled: true
  compression.enabled: true

management:
  endpoints:
    web.exposure.include: health

spring:
  ai.openai.chat.options:
    model: gpt-4o
    temperature: 0.7
  threads.virtual.enabled: true
  jmx.enabled: false
