server:
  http2.enabled: true
  compression.enabled: true

management:
  endpoints:
    web.exposure.include: health

spring:
  ai:
    ollama:
      base-url: http://ollama:11434
      chat.options:
        model: qwen2:1.5b
        temperature: 0.7
        keep_alive: 60m
        num-thread: 1

threads.virtual.enabled: true
jmx.enabled: false
