baseurl: http://localhost:8080<
api-key: <your-api-key>

server:
  http2.enabled: true
  compression.enabled: true

management:
  endpoints:
    web.exposure.include: health

pushover:
  enabled: false
  api-key: <your pushover api key>
  user-key: <your user key>

spring:
  ai:
    ollama:
      base-url: http://<enter URL to ollama>
      chat.options:
        model: <enter model name> # e.g. deepseek-r1:1.5b
        temperature: 0.7
        keep_alive: 35m
        num-thread: <number of CPU threads>

  data.mongodb:
    host: <host>
    port: <port>
    authentication-database: <auth-db>
    username: <username>
    password: <password>
    database: <dbname>

threads.virtual.enabled: true
jmx.enabled: false