baseurl: http://localhost:8080<
api-key: <your-api-key>

spring:
  data.mongodb:
    host: <host>
    port: <port>
    authentication-database: <auth-db>
    username: <username>
    password: <password>
    database: <dbname>
